### ISSUE TITLE
Tap Away from Nav

### ISSUE THREAD

**Issue by Chrisawgey** [Chrisawgey/CGB-test-web#2]
### Click Away
in mobile or desktop we should have a option to click out of the nav anywhere on the screen so it can just slide up
@homierdawg

**Comment by homierdawg** [comment]
just put it in crosh

**Comment by Chrisawgey** [comment]
command top @homierdawg

**Comment by Chrisawgey** [comment]
<a href="#" class="icon" id="myButton"> 

java 
const button = document.getElementById('myButton');
const div = document.getElementById('myLinks');
const icon = document.querySelector('.icon');
console.log(icon);

document.addEventListener('click', myFunction)

function myFunction(e) {
  e.preventDefault();
  console.log(e.target);
  
  if((div.style.display === '' || div.style.display === 'none') && (e.target === button || e.target === itag)) {
    div.style.display = 'block';    
  } else if((div.style.display === '' || div.style.display === 'none') && (e.target !== button || e.target !== itag)) {
    div.style.display = 'none';
  } else {
    div.style.display = 'none';
  }
}

**Comment by Chrisawgey** [comment]
@homierdawg  

http://jsfiddle.net/evGd6/2/

**Comment by Chrisawgey** [comment]
https://codepen.io/alac1984/pen/RwNVKOe maybe maybe
